# Generated by Django 3.0.8 on 2020-08-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20200809_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='username',
            field=models.CharField(max_length=128, unique=True, verbose_name='사용자명'),
        ),
    ]
